title: Robson Calixto
email: robsoncaliixto@gmail.com

#description: >-
  #Write an awesome description for your new site.

baseurl: "/personalBlog"
url: "https://barbarakarvalho.github.io"
twitter_username: jekyllrb
github_username: https://github.com/robsoncalixto

theme: minima
plugins:
  - jekyll-feed